server:
  port:
    8082
spring:
  http:
    encoding:
      charset:
        UTF-8
      enabled:
        true
      force:
        true
  messages:
    encoding:
      UTF-8
  jackson:
    default-property-inclusion:
      non_null
  datasource:
    driver-class-name:
      com.mysql.jdbc.Driver
    url:
      jdbc:mysql://47.96.89.99:3306/authorize?characterEncoding=utf-8
    username:
      root
    password:
      ytaotao

  redis:
    ip: 47.96.89.99
    port: 6379
    password: ytaotao
    timeout: 3000
    database: 0
    pool:
      maxTotal: 300
      maxWaitMillis: 10000
      testOnBorrow: true
      testOnReturn: true
      testWhileIdle: true
      maxIdle: 100
      minIdle: 30

